gitlab4j#1023 Add Field Iteration to Issue.
gitlab4j/gitlab4j-api pull request #1027
Opened 2023-08-31 13:54 UTC by KoCoder

+ Iteration Class
+ Getter and Setter for Iteration field

closes https://github.com/gitlab4j/gitlab4j-api/issues/1023

2023-09-04 15:19 UTC, jmini requested changes
The change looks good to me. Just a test case is missing.

2023-09-04 15:19 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/Iteration.java
There should be a test case with an example JSON

* new json example in `src/test/resources/org/gitlab4j/api/`. Example `iteration.json`
* new test method `TestGitLabApiBeans`.

2023-09-04 15:19 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/AbstractIssue.java
To verify:

This `AbstractIssue` class is shared between multiple concrete classes.

we should verify where the `iteration` attribute is available.

2023-09-08 16:20 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/AbstractIssue.java
In `EpicIssue` it is available.

```
GET <server>/api/v4/groups/:id/epics/:epic_iid/issues
```

In `LinkedIssue` it is available as well:
```
GET <server>/api/v4/projects/:project/issues/:issue_iid/links
```

So adding it in `AbstractIssue` is correct

2023-09-08 19:05 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/Iteration.java
> +	private IterationState state;
In the json, the state is an integer:

https://gitlab.com/gitlab-org/gitlab/-/blob/4db027c5a18a8638bb0e6103b49010975058a9f8/doc/api/iterations.md#L56

2023-09-08 19:06 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/Iteration.java
> +	private String descripion;
There is a typo: Should be `description`

2023-09-08 19:09 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/Iteration.java
> +	private IterationState state;
From the code:
https://gitlab.com/gitlab-org/gitlab/-/blob/4db027c5a18a8638bb0e6103b49010975058a9f8/ee/app/models/iteration.rb#L14-18

It seems that there are only 3 possible values.

2023-09-14 14:37 UTC, jmini commented
@KoCoder you did not grant `Maintainers are allowed to edit this pull request` on this PR.

I made the requested changes in https://github.com/jmini/gitlab4j-api/commit/f3cb01cd39a435cd506bf3120f7f03777267fcd5

Can you add that to this PR (on the branch `heek-feature-gitlab4j-1023-iterations`)?

Or should I re-create an other PR to get this change integrated?

2023-09-18 14:35 UTC, KoCoder commented
Hey, I've just cherry-picked your changes onto our feature branch.

2023-09-19 04:51 UTC, jmini approved these changes

2023-09-19 09:29 UTC, merged

2023-10-30 22:45 UTC, PaulWoitaschek commented
@jmini 
Could you cut a release with this change included? Alternatively: Do snapshots get published of gitlab4j?