Add the "internal" flag to NotesApi.createIssueNote()
gitlab4j/gitlab4j-api pull request #1029
Opened 2023-09-08 08:44 UTC by hannibal218bc

- add a new `createIssueNote()` method allowing to pass the `internal` flag.
- add the `internal` flag to the `Note` model

2023-09-08 15:18 UTC, jmini requested changes
Please also add the `internal` flag to the example file:
https://github.com/gitlab4j/gitlab4j-api/blob/main/src/test/resources/org/gitlab4j/api/note.json
--> this should be as close as possible to a real object returned by GitLab.

This way this test make sure our model matches with the JSON example:

https://github.com/gitlab4j/gitlab4j-api/blob/ff037bd36355a7391d3ba7a7c417410d3cbf3612/src/test/java/org/gitlab4j/api/TestGitLabApiBeans.java#L681-L685

... and your addition is covered checked by a test.

2023-09-08 15:18 UTC, jmini commented on src/main/java/org/gitlab4j/api/NotesApi.java
> +        }
No need to check for the internal value. If you use `Boolean` the `withParam` adds it only if not null.

```suggestion
                .withParam("created_at", createdAt)
                .withParam("internal", internal);
```

2023-09-08 15:18 UTC, jmini commented
@hannibal218bc thank you for this PR. Small changes are requested but the change looks almost good to me.

2023-09-14 19:27 UTC, hannibal218bc commented
> @hannibal218bc thank you for this PR. Small changes are requested but the change looks almost good to me.

@jmini thank you for the feedback. I'll submit the changes as soon I as time permits.

2023-09-18 09:45 UTC, jmini commented on src/main/java/org/gitlab4j/api/NotesApi.java
> +        return (createIssueNote(projectIdOrPath, issueIid, body, null, false));
```suggestion
        return (createIssueNote(projectIdOrPath, issueIid, body, null, null));
```

2023-09-22 20:29 UTC, hannibal218bc commented
@jmini thank you for the review, I've updated the MR with the requested changes.

> Please also add the `internal` flag to the example file: https://github.com/gitlab4j/gitlab4j-api/blob/main/src/test/resources/org/gitlab4j/api/note.json --> this should be as close as possible to a real object returned by GitLab.

I cross-checked the file against a file retrieved from a 16.4 enterprise instance, and there are a few more differences - added `attachments`, `confidential`,  but `author.created` is missing. And a new field `type` that isn't even documented at Gitlab...

I guess the JSON shall only contain properties that are actually supported by Gitlab4J?

2023-09-25 09:08 UTC, jmini commented
> I guess the JSON shall only contain properties that are actually supported by Gitlab4J?

Sadly this is the long work of keeping our model aligned with the JSON returned by GitLab. Step by step we are getting closer.

I agree that the field you mention are out of scope for this pull request.

> And a new field `type` that isn't even documented at Gitlab

This is crazy. They have also issue keeping up-to-date their doc with their code.

2023-09-25 09:36 UTC, jmini approved these changes
It looks good to me. I will do some manual testing before merging.

2023-09-26 07:38 UTC, merged