added new api call for forced push checks #1071
gitlab4j/gitlab4j-api pull request #1072
Opened 2023-12-19 11:25 UTC by dpalic

here a change to expose the forced commit check to gitlab4j too

2023-12-19 11:26 UTC, dpalic commented
with the new 6.0 release the api change may be okay, since everyone expects to do minor changes on major change

2023-12-20 11:16 UTC, jmini commented on src/main/java/org/gitlab4j/api/ProtectedBranchesApi.java
> +        //FIXME: cannot test, having CE only to test
I don't think we need this FIXME line in the code.

```suggestion
```

If you know how we could have access to a Testing-Ultimate version, that would be great. I have this on my list, but I would need to ask somebody at GitLab.

2023-12-20 13:21 UTC, jmini commented on src/main/java/org/gitlab4j/api/ProtectedBranchesApi.java
> +            Boolean codeOwnerApprovalRequired, Boolean allowForcedPush) throws GitLabApiException {
Usually when we add a new parameter we also add a method with the old signature (using java method overloading) to preserve backward compatibility.

2023-12-20 13:21 UTC, jmini commented on src/main/java/org/gitlab4j/api/ProtectedBranchesApi.java
> +            Boolean codeOwnerApprovalRequired, Boolean allowForcedPush) throws GitLabApiException {
Usually when we add a new parameter we also add a method with the old signature (using java method overloading) to preserve backward compatibility.

2023-12-20 17:22 UTC, jmini requested changes
The change looks good to me, but the changes described in the comments are needed

2023-12-25 16:10 UTC, dpalic commented
changed the reported issues, would be great if you could check and merge into master for next major release

2023-12-26 11:40 UTC, jmini commented on src/main/java/org/gitlab4j/api/ProtectedBranchesApi.java
> +        if (Objects.nonNull(allowForcedPush)) {
The `if` here is not necessary. The method `.withParam(..)` is already taking care of that.

2023-12-26 13:14 UTC, jmini approved these changes
I made some additional changes.
I will perform some manual tests and merge

2023-12-26 13:14 UTC, jmini commented on src/main/java/org/gitlab4j/api/ProtectedBranchesApi.java
> +        if (Objects.nonNull(allowForcedPush)) {
Fixed with 7ad47ca0769bc88867208a1e2756d5e8d266e5fa

2023-12-26 19:38 UTC, merged