Add missing deployment and enviorment attributes
gitlab4j/gitlab4j-api pull request #1187
Opened 2024-10-28 12:21 UTC by katrinSaleschus

2024-11-07 06:22 UTC, jmini requested changes
Some tests should be added

2024-11-07 06:22 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/Environment.java
Please update the corresponding json file (add a realistic example value): [environment.json](https://github.com/gitlab4j/gitlab4j-api/blob/c393f61a5aec8cb916da6b19b974ee67ba800979/src/test/resources/org/gitlab4j/api/environment.json)

This is tested by this test:
https://github.com/gitlab4j/gitlab4j-api/blob/c393f61a5aec8cb916da6b19b974ee67ba800979/src/test/java/org/gitlab4j/api/TestGitLabApiBeans.java#L171-L175

2024-11-07 06:22 UTC, jmini commented on src/main/java/org/gitlab4j/api/webhook/DeploymentEvent.java
There is not test, but this should be tested in [`TestGitLabApiEvents`](https://github.com/gitlab4j/gitlab4j-api/blob/c393f61a5aec8cb916da6b19b974ee67ba800979/src/test/java/org/gitlab4j/api/TestGitLabApiEvents.java)

2024-11-13 15:28 UTC, katrinSaleschus commented
Thank you for your Review. Now everything should be ok to merge.

2024-11-18 05:35 UTC, jmini commented
I will have a look

2024-11-28 19:27 UTC, merged