Add support for email on push integration.
gitlab4j/gitlab4j-api pull request #662
Opened 2021-02-23 21:01 UTC by ttaxon

This adds support for the Emails on push integration.

2021-03-01 17:44 UTC, jabby requested changes
Thanks for this PR. I didn't try your patch yet. 
Here are few remarks. Can you please take care of them?

2021-03-01 17:44 UTC, jabby commented on src/main/java/org/gitlab4j/api/ServicesApi.java
> +     * Get the Custom Issue Tracker service settings for a project.
Can you update javadoc accordingly to gitlab documentation? https://docs.gitlab.com/ee/api/services.html#emails-on-push

2021-03-01 17:44 UTC, jabby commented on src/main/java/org/gitlab4j/api/ServicesApi.java
> +     * Updates the Custom Issue Tracker service settings for a project.
Can you update javadoc accordingly to gitlab documentation? https://docs.gitlab.com/ee/api/services.html#emails-on-push

2021-03-01 17:44 UTC, jabby commented on src/main/java/org/gitlab4j/api/ServicesApi.java
> +     * Deletes the Custom Issue Tracker service for a project.
Can you update javadoc accordingly to gitlab documentation? https://docs.gitlab.com/ee/api/services.html#emails-on-push

2021-03-01 17:44 UTC, jabby commented on src/main/java/org/gitlab4j/api/services/EmailOnPushService.java
> +    public static final String SEND_FROM_COMMITTER_EMAIL = "send_from_committer_email";
`SEND_FROM_COMMITTER_EMAIL` should be named `SEND_FROM_COMMITTER_EMAIL_PROP`

2021-03-01 17:44 UTC, jabby commented on src/main/java/org/gitlab4j/api/services/EmailOnPushService.java
> +    public static final String BRANCHES_TO_BE_NOTIFIED = "branches_to_be_notified";
`BRANCHES_TO_BE_NOTIFIED` should be named `BRANCHES_TO_BE_NOTIFIED_PROP`.

2021-03-01 17:44 UTC, jabby commented on src/main/java/org/gitlab4j/api/services/EmailOnPushService.java
> +	}
Please fix the identation here.

2021-03-03 01:26 UTC, ttaxon commented
All edits have been made.

2021-03-22 12:43 UTC, jabby commented
Thanks @ttaxon 
I will provide some automated tests in another PR

2021-03-22 12:44 UTC, merged