Add headPipeline to MergeRequest
gitlab4j/gitlab4j-api pull request #890
Opened 2022-12-22 03:46 UTC by vimsucks

[https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr)

![image](https://user-images.githubusercontent.com/21141423/209051196-e29bace8-e617-4ab3-8bb7-e34092cb07ad.png)

![image](https://user-images.githubusercontent.com/21141423/209051029-881b5804-8e02-4eca-8952-d7416ed390cf.png)

2023-03-17 09:11 UTC, jmini requested changes
I would do minor changes to be consistent with the rest of the code. But for me this change looks good to me.

2023-03-17 09:11 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/MergeRequest.java
> +    }
In this project the setters are returning `void`.

When an attribute is used to create or update an entity, there is a builder method `withHeadPipeline(..)` next to the setter.
But in this case the `head_pipeline` attribute is only used during a read, so the builder method makes no sense.

```suggestion
    public void setHeadPipeline(Pipeline headPipeline) {
        this.headPipeline = headPipeline;
    }
```

2023-03-17 09:11 UTC, jmini commented on src/main/java/org/gitlab4j/api/models/Pipeline.java
> +    }
Same here:

```suggestion
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }
```

2023-04-18 10:03 UTC, vimsucks commented
> I would do minor changes to be consistent with the rest of the code. But for me this change looks good to me.

thanks! suggestion applied

2023-04-19 16:35 UTC, jmini approved these changes

2023-04-19 16:35 UTC, merged