#954 add include_retried for jobs api
gitlab4j/gitlab4j-api pull request #955
Opened 2023-04-14 09:27 UTC by vmtrue

2023-04-14 12:05 UTC, jmini requested changes
I would do some minor changes (please review the suggestions carefully, I am not sure about them), but otherwise this looks good to me.

2023-04-14 12:05 UTC, jmini commented on src/main/java/org/gitlab4j/api/JobApi.java
>          return (response.readEntity(new GenericType<List<Job>>() {}));
Here I would just delegate to the other method:

```suggestion
        return getJobsForPipeline(projectIdOrPath, pipelineId, null, includeRetried)
```

2023-05-25 08:53 UTC, jmini approved these changes
I have applied the requested changes and fixed the compile error.

I also merged the main branch into this PR.

2023-06-13 15:33 UTC, jabby approved these changes

2023-06-13 15:33 UTC, merged