add reviewers to EventChanges.java
gitlab4j/gitlab4j-api pull request #958
Opened 2023-04-17 19:04 UTC by mifitous

This PR will add the missing reviewers fields to the EventChanges

- ChangeContainer<List<Reviewer>> reviewers at top level of EventChanges.java
https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events

Fix for issue https://github.com/gitlab4j/gitlab4j-api/issues/820

2023-04-17 19:16 UTC, mifitous commented
@jetersen / @jmini :
Please kindly can you merge this one as well?
Than you a lot

2023-04-18 10:16 UTC, jetersen approved these changes

2023-04-19 10:12 UTC, jmini requested changes
Please update the example file:

https://github.com/gitlab4j/gitlab4j-api/blob/69ba436c71f9d76109a957c70b8fae0577cfacb8/src/test/resources/org/gitlab4j/api/merge-request-event.json#L132

By adding a new `reviewers` attribute:

```
  "changes": {
    ....
    "reviewers": {
      "previous": [
        {
          "id": 2,
          "name": "John Doe",
          "username": "jdoe",
          "avatar_url": "https://www.gravatar.com/avatar/0?s=80&d=identicon",
          "email": "jdoe@example.com"
        }
      ],
      "current": [
        {
          "id": 3,
          "name": "Paul Smith",
          "username": "psmith",
          "avatar_url": "https://www.gravatar.com/avatar/0?s=80&d=identicon",
          "email": "psmith@example.com"
        }
      ]
    }
  },
```

2023-04-19 10:12 UTC, jmini commented on src/main/java/org/gitlab4j/api/webhook/EventChanges.java
> +    private ChangeContainer<List<Reviewer>> reviewers;
I am not sure this is correct here.

This class is shared between `IssueChanges` and `MergeRequestChanges` and the `reviewers` attribute is something that only makes sense in the context of a MR.

So I think it should be added only to `MergeRequestChanges`.

2023-04-19 11:22 UTC, mifitous commented
Hi @jmini : changes implemented
Thanks for your feedback

2023-04-19 12:17 UTC, jetersen approved these changes

2023-04-19 16:32 UTC, jmini approved these changes

2023-04-19 16:32 UTC, merged

2023-04-20 06:38 UTC, mifitous commented
Thanks @jmini 
Can you please trigger a release of a new version? 5.2.1/5.3.0?
Thank you